### ISSUE TITLE
Consider deprecating this gem in favor of font-awesome-rails

### ISSUE THREAD

**Issue by rmm5t** [tadast/fontawesome-rails#3]
In an effort to avoid community confusion, I'd like to propose deprecating this gem in favor of [bokmann/font-awesome-rails](https://github.com/bokmann/font-awesome-rails). Font-awesome-rails has actually received at least one bug report that should have been reported here instead.

**Reasons:** The font-awesome-rails gem...
- tracks Font-Awesome core very closely.
- has a test suite
- including test matrices for Rails 3.2, Rails 4.x, and Rails 5.
- works when fonts are stored on a CDN (like CloudFront)
- doesn't require sass or less, but 
- still works with sass imports 
- includes view helpers for rendering different kinds of icon formats

Consolidating everyone's efforts into one canonical rails engine is a win.

font-awesome-rails is basically a drop-in replacement for fontawesome-rails, but with some extras.

If you're open to this, I suggest:
1. Clearing out the repository, but
2. Leave just a README with a pointer and explanation that font-awesome-rails should be used instead.

(I'm happy to submit a pull-request with this deprecation to save you time.)

Thoughts?

**Comment by mjc-gh** [comment]
@tadast has given me access to help maintain this gem. @SimplyBuilt uses this gem and we will keep it up to date moving forward. We need something really lightweight (no helpers or sass-rails dependency).

Perhaps bokmann/font-awesome-rails dependencies can be whittled down?

**Comment by rmm5t** [comment]
> @tadast has given me access to help maintain this gem. 

Congrats.

> We need something really lightweight (no helpers or sass-rails dependency).

**Re: no helpers**: Without any sound argument to go with it, I think that's somewhat of a pointless stand to take. Assets gems with no functionality have some merit, but they provide more benefit when they also  offer (well-tested) helpers -- especially if they help facilitate the 99% use case.

> Perhaps bokmann/font-awesome-rails dependencies can be whittled down?

I think you're misunderstanding how the dependencies work. `font-awesome-rails` doesn't depend on `sass-rails`. **bokmann/font-awesome-rails has exactly one dependency: `railties`**. It can't get any lighter than that for a rails engine. Read the gemspec.

Aside, we occasionally get bug reports on font-awesome-rails because people accidentally include this gem (fontawesome-rails) instead and it breaks things or doesn't work as expected. I'm glad there's now a maintainer to send these bug reports to.

If you want to continue maintaining this gem, that's great. Rock on, but I think it's a fruitless effort by not adding much value to the community. Possibly only adding confusion. 

Right now, people primarily use one of two gems for wrapping FontAwesome. bokmann/font-awesome-rails (for a lightweight wrapper, upgrades within 24 hours of an official FontAwesome release, semantic versioning, helpers, and wide coverage on the test/build matrix) or fortawesome/font-awesome-sass (for sass plugins even though, ironically, it doesn't keep up with version bumps, and lacks a test suite).

**Comment by mjc-gh** [comment]
I assure you I understand how Gem dependencies work. However, I misread a development dependency as a hard dependency, my apologizes.

While I really do not need the helpers for my use cases, I do agree the less gems for the same task, the better! If it's OK with @tadast we can shutdown this project and have this project point to bokmann/font-awesome-rails.

I can update this project and the README once I get a go ahead.

**Comment by tadast** [comment]
Go for it 👍

**Comment by mjc-gh** [comment]
Thanks @tadast!

**Comment by tadast** [comment]
Can we add a post-install message to the gem so that the users would get
notified after bundling if they chose this gem by mistake?

**Comment by mjc-gh** [comment]
I can look into that later. Maybe push one last minor version release that has a very loud deprecation warning message for its post install message.

**Comment by mjc-gh** [comment]
Alright, made a branch for it. Will now get something like:

```
$ gem install fontawesome-rails-4.0.3.2.gem 
DEPRECATED: This gem has been deprecated in favor of font-awesome-rails.
...
```

Anything else we should add to the message @rmm5t?

**Comment by rmm5t** [comment]
@mikeycgto Looks good. Nice work. Thanks.
